### ISSUE TITLE
NIST compliance of KEM-combiner w.r.t. X25519/X448 KEM 

### ISSUE THREAD

**Issue by falko-strenzke** [openpgp-pqc/draft-openpgp-pqc#132]
In https://github.com/openpgp-pqc/draft-ehlen-openpgp-nist-bp-comp/issues/10#issuecomment-2220090284 Quynh states that the current construction with a key derivation step in ECDH-KEM is not NIST compliant, which would equally affect the X25519/X448 KEM construction in this draft:

> So, if we delete the step 3 in ECDH-KEM ( Set the output eccKeyShare to Hash(X || eccCipherText || eccPublicKey),  then Falko's suggested KDF is NIST-compliant.

> If we keep the step 3, eccKeyShare is a pseudorandom key and if eccKeyShare takes the place of X in Falko's suggested KDF, the KDF is not NIST-compliant at this point, but the KMAC-KDF mentioned above is NIST-compliant.

@QuynhDangNIST: can you provide the exact clause in the NIST standards that causes the incompliance? So far it seems to me that the using the output of ` Hash(X || eccCipherText || eccPublicKey)`  is equally fine to use as the ECC shared secret as input to the KEM combiner given by SHA3-256.

If the construction would really turn out to not being NIST compliant, we would have to change it in this draft as well.

**Comment by falko-strenzke** [comment]
I just want to add that from my point of view, just as I proposed here in said [issue #10 of the NIST/Brainpool draft](in https://github.com/openpgp-pqc/draft-ehlen-openpgp-nist-bp-comp/issues/10#issuecomment-2213190813) for the Weiherstrass-Curves, from my point of view the Hashing step in the X25519/X448 KEM can be dropped since we feed the public key and the ciphertext already to the key combiner KDF.

**Comment by QuynhDangNIST** [comment]
See Section 2 on page 2 of 56Cr2 here: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf

Z' = Z || T.  Z is a raw shared secret as specified in 56A,B&C, not a pseudorandom key.  A KDF specified in 56C is used to generate pseudorandom key(s) from Z or Z'.

Right now, the KDFs in 56C are NIST-compliant only when H(counter || Z || FixedInfo) on page 14 has Z being a raw shared secret or Z' above. The situation where "counter" can be skipped was explained in my previous email.

Regards,
Quynh.

From: Falko Strenzke ***@***.***>
Sent: Wednesday, July 10, 2024 6:37 AM
To: openpgp-pqc/draft-openpgp-pqc ***@***.***>
Cc: Dang, Quynh H. (Fed) ***@***.***>; Mention ***@***.***>
Subject: [openpgp-pqc/draft-openpgp-pqc] NIST compliance of KEM-combiner w.r.t. X25519/X448 KEM (Issue #132)


In openpgp-pqc/draft-ehlen-openpgp-nist-bp-comp#10 (comment)<https://github.com/openpgp-pqc/draft-ehlen-openpgp-nist-bp-comp/issues/10#issuecomment-2220090284> Quynh states that the current construction with a key derivation step in ECDH-KEM is not NIST compliant, which would equally affect the X25519/X448 KEM construction in this draft:

So, if we delete the step 3 in ECDH-KEM ( Set the output eccKeyShare to Hash(X || eccCipherText || eccPublicKey), then Falko's suggested KDF is NIST-compliant.

If we keep the step 3, eccKeyShare is a pseudorandom key and if eccKeyShare takes the place of X in Falko's suggested KDF, the KDF is not NIST-compliant at this point, but the KMAC-KDF mentioned above is NIST-compliant.

@QuynhDangNIST<https://github.com/QuynhDangNIST>: can you provide the exact clause in the NIST standards that causes the incompliance? So far it seems to me that the using the output of Hash(X || eccCipherText || eccPublicKey) is equally fine to use as the ECC shared secret as input to the KEM combiner given by SHA3-256.

If the construction would really turn out to not being NIST compliant, we would have to change it in this draft as well.

-

**Comment by falko-strenzke** [comment]
> See Section 2 on page 2 of 56Cr2 here: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf

@QuynhDangNIST Ist the point that if we have the hashing step in the ECDH-KEM and in the key combiner, that then we effectively do something like `key = hash(hash(X || ...) || ... )`, i.e., that contrary to NIST.SP.800-56Cr2 we hash twice?

**Comment by falko-strenzke** [comment]
OK, to be more precise, what we currently do is 

```
key = hash( counter || hash(X || ...) || ... )
```
But still my question is what exactly is causing the non-conformance in your view. The only deviation from 56C that I can identify is that instead of feeding `X` directly to the outer hash function we feed `hash(X || ...)`. Is that reason for the incompliance that you were speaking of?

**Comment by falko-strenzke** [comment]
@QuynhDangNIST And a further question: will this incompliance also be given when the ECDH scheme is X25519 or X448?

**Comment by QuynhDangNIST** [comment]
I don't understand what part of the things I have written today is not clear to you.

I am not talking about security.  I have been talking about what KDFs are NIST-compliant and what are not.

Quynh.

**Comment by QuynhDangNIST** [comment]
Hi Falko,

I don't know for sure what specific KDF this question ***@***.*** And a further question: will this incompliance also be given when the ECDH scheme is X25519 or X448? " was for.

In the past, NIST said that NIST planned to allow X25519 and/or X448 for ECDH. But at this moment, they are not the options in 56A.

I can talk to my group to see whether that is still in the plan. Especially, when we want people to use PQ crypto.

Regards,
Quynh.

**Comment by falko-strenzke** [comment]
> I can talk to my group to see whether that is still in the plan. Especially, when we want people to use PQ crypto.

Maybe that can wait until we decided which way we prefer. If we remove the incompliance anyway, this would be better in my view.

**Comment by falko-strenzke** [comment]
Here is my summary to the problem as I understand it:

In [NIST.SP.800-56Cr2](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Cr2.pdf#page=10), page 2 it says

> derive keying material from a shared secret Z generated during the execution of a key-establishment scheme specified in ...

So the shared secret that is input to the key derivation of the key combiner will have to be

    Z′ = Z || T,

where `Z` is the raw shared secret from the ECDH scheme and `T` in our case is the ML-KEM key share. Then the SHA3-based construction that we are specifying for the key combiner becomes:

    SHA3-256(counter || Z || T || <other input>),

where `<other input>` is the public keys, ciphertexts, domain separation string, and algorithm ID. This is how it should be done according to SP.800-56C.

Now the problem that causes the non-compliance apparently is that in our current specification, we don't input `Z` as shown above, but instead `hash(Z ||  ecdhCipherText || ecdhPublicKey)`. This additional hashing step is a formal deviation from the NIST spec.

The NIST-compliance is definitely relevant to the draft for the NIST/Brainpool curves. But since X25519/X448 is considered by NIST to receive NIST compliance as well, it has a certain relevance to the main draft as well.

The solution would be omitting the hashing step from the ECDH specification. Then we input the raw shared secret from the ECDH scheme into the key combiner as required by NIST. I don't think there can be any drawback, as the ECDH public key and ciphertext are still input as part of `<other input>` above.

The alternative that Quynh pointed out is to keep using KMAC. The formal difference seems to stem from the fact that in [NIST.SP.800-108r1](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-108r1-upd1.pdf#page=10) it says that the input keys may stem from  "[...] or a previous instance of key derivation as specified in this Recommendation" (p. 2) and thus allows to use KMAC with `hash(Z || ...) || T` as the input. That this does not equally apply to SHA3 is simply due to SP.800-108r1 not specifying SHA3 as a KDF at all.

**Comment by QuynhDangNIST** [comment]
Hi Falko,

**Comment by falko-strenzke** [comment]
There is one risk that I see for the solution using
```
SHA3-256(counter || <raw EC coord.> || <ML-KEM ss> || <other input>).
```
We agree that this will result in a NIST compliant ECDH scheme with an additional key mixed in.
    But I currently don't see the guarantee that this will also necessarily fulfill the future requirements by NIST for an ECDH+ML-KEM hybrid scheme. This is something that we will most likely only know once NIST's recommendations for PQ/T hybrid is specified. The other solution, namely switching back to KMAC does not have this problem, since with KMAC we receive a generic KDF according to NIST.SP.800-108r1. Thus in this case there is no limitation on where the input secrets to the KMAC-based KDF stem from.

**Comment by ahuelsing** [comment]
Dear all, Falko asked me to provide a comment on this.

I would like to highlight two aspects here. First, our goal is to build a "KEM-combiner", i.e., something that constructs a secure KEM from two KEMs. The initial hash of the ECDH data achieves exactly this: It turns DH into a KEM. This way, we are able to apply modular reasoning which also protects against issues stemming from replacing ECDH by some other construction. 

Second, our set goal is really to construct an IND-CCA secure KEM. This is a mismatch with https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar3.pdf  which describes how to derive a secret key from some source of computational entropy (like a pre-master secret) where one such source is obtained via DH. Note that while the SP this does not explicitly state any security goals (at least I did not find any), the way it is written suggests that active security is not a concern here. 

Regarding what we know in terms of results: We have a security proof for a KEM that is obtained by combining the data of two KEMs as is currently done in the draft (KDF(k1,c1,pk1,k2,c2,pk2) where the order does not matter if we use SHA3/SHAKE/KMAC-SHA3). This proof is in the standard model and thereby holds against quantum adversaries as well. I do not know what we can prove for the "simply hashing everything in the end" approach (KDF(DH.k, k2, DH.pk_sender, DH.pk_receiver, c2, pk2)). This will require a direct, non-modular proof for the full construction. Does NIST have any results for this? I did not see references in the SP.

Best wishes,

Andreas

**Comment by wussler** [comment]
Hi @QuynhDangNIST

Do we need all steps of KDF to be FIPS-compliant to achieve FIPS compliance? 

If so, please let me propose a solution if I parsed correctly all the info in the thread:
- We can use an SP.800-56Cr2 compliant KDF in the ECDH KDF, that is already `SHA3-256(X || ecdhCipherText || ecdhPublicKey)`
- We rely on SP.800-108r1 and switch to KMAC for the KEM Combiner as KMAC(K, X, 256, "KDF"), where K is the concatenated keys (?) and X are the ciphertexts and public keys?

Would that be compliant?

**Comment by QuynhDangNIST** [comment]
Hi Aron,

See below.

________________________________
