### ISSUE TITLE
Reference use of pre-hash variant of FIPS 204 and 205 (in case we will use it)

### ISSUE THREAD

**Issue by falko-strenzke** [openpgp-pqc/draft-openpgp-pqc#135]
- #142
  - Need to provide OIDs for specified PH algorithms for both schemes 
  - Explain how to use the pre-hash, explain what is `PH_M`
  - In the introd., where ML-DSA and SLH-DSA is mentioned first, the choice of Pre-hash should be mentioned

**Comment by falko-strenzke** [comment]
On the list, I voted to drop the topic and simply use the pure variant to sign the hash. That's not perfect in my view, but NIST's specification in FIPS 204 is too unclear to make the point that it is intended to use the pre-hash variant in our case. For OpenPGP, this decision has no security implications anyway. I propose to close this issue.

**Comment by TJ-91** [comment]
I think we should wait a bit for the discussion on the OpenPGP mailing list to conclude, as well as your request for clarification on the NIST mailing list.

**Comment by fluppe2** [comment]
After discussion with @falko-strenzke and @wussler, I will clarify throughout the text that we use the pure version of ML-DSA and SLH-DSA.
