### ISSUE TITLE
SLH-DSA-SHAKE or SLH-DSA

### ISSUE THREAD

**Issue by fluppe2** [openpgp-pqc/draft-openpgp-pqc#143]
I found SLH-DSA-SHAKE to cause some problems:
- The abstract says "SLH-DSA-SHAKE (formerly SPHINCS+)". I don't think this is correct, rather SLH-DSA is the new name of the former SPHINCS+ framework.
- The intro (and I guess several other places" cites "SLH-DSA-SHAKE [FIPS-205]". I don't think this is correct, but rather "SLH-DSA [FIPS-205]".
- Section "1.2.3 SLH-DSA-SHAKE" uses this terminology without introducing/explaining it.

I would rather prefer to switch back to "SLH-DSA" and not have this new name "SLH-DSA-SHAKE" that might cause confusion. Rather say when we define the codepoints that we restrict to the SHAKE parameter sets.

**Comment by TJ-91** [comment]
> The abstract says "SLH-DSA-SHAKE (formerly SPHINCS+)". I don't think this is correct, rather SLH-DSA is the new name of the former SPHINCS+ framework.

I would go one step further and simply drop mentioning the former names of the algorithms.

> I would rather prefer to switch back to "SLH-DSA"

I agree.

**Comment by falko-strenzke** [comment]
> > I would rather prefer to switch back to "SLH-DSA"
> 
> I agree.

I agree also. It is sufficient to mention "SHAKE" as the PRF in table  #sig-alg-specs. The remainder of the document should only refer to "SLH-DSA".
