### ISSUE TITLE
Introductory section on Elliptic Curve Cryptography

### ISSUE THREAD

**Issue by fluppe2** [openpgp-pqc/draft-openpgp-pqc#144]
I feel that the text in section "1.3 Elliptic Curve Cryptography" outdated? Shouldn't we actually refer to X25519, X448 and EdDSA?

**Comment by fluppe2** [comment]
I think we have the same text in front of us.

I would just spell out the algorithm names along with pointing to their RFCs. That would make it much clearer that this specification only does X and Ed.

e.g.

"The ECDH encryption is defined here as a KEM via X25519 and X448 which are defined in [RFC7748]. EdDSA as defined in [RFC8032] is used as the elliptic curve-based digital signature scheme."

instead of the present

The ECDH encryption is defined here as a KEM. Curve25519 and Curve448 are defined in [RFC7748] for use in a Diffie-Hellman key agreement scheme and defined in [RFC8032] for use in a digital signature scheme.

---
Maybe I am to pedantic here.

**Comment by falko-strenzke** [comment]
> "The ECDH encryption is defined here as a KEM via X25519 and X448 which are defined in [RFC7748]. EdDSA as defined in [RFC8032] is used as the elliptic curve-based digital signature scheme."

I am fine with this proposed change. I wouldn't see it as ultimately necessary, but I think it's a further clarification of the text.
