### ISSUE TITLE
Test Vectors: Hash Binding

### ISSUE THREAD

**Issue by TJ-91** [openpgp-pqc/draft-openpgp-pqc#153]
The -05 test vectors do not respect the hash binding that is mandated in https://datatracker.ietf.org/doc/html/draft-ietf-openpgp-pqc-05#tab-mldsa-hash. Instead, SHA256 and SHA512 are used.

**Comment by falko-strenzke** [comment]
@TJ-91  Please make this two issues. The two points have nothing to do with each other.
