### ISSUE TITLE
From pqc@ietf: Summary OpenPGP crypto functions and further references

### ISSUE THREAD

**Issue by fluppe2** [openpgp-pqc/draft-openpgp-pqc#16]
In view of

https://mailarchive.ietf.org/arch/msg/pqc/rX2AcijHUbdiijehEaZS5PmpulQ/

address (how?) the following

>> I think it would also benefit from a intro section that summarizes OpenPGP Crypto functions. ... Even references to the proper RFCs for more info would be beneficial.

> This RFC is designed to be an addition to the crypto-refresh (what the WG is working on right now), and is directly based on it. I think you're right about the references, and it could be very beneficial to add more links to it, with specific references to the sections.

**Comment by wussler** [comment]
Personally I think there are still some places where we can add backreferences, especially when we introduce packets or so on. This is mostly cosmetic, and I can take care of this.

**Comment by falko-strenzke** [comment]
I think we can oriented towards RFC 6637 in this respect. [There](https://www.rfc-editor.org/rfc/rfc6637#section-9), it is written for instance

```
9. Encoding of Public and Private Keys

   The following algorithm-specific packets are added to Section 5.5.2
   of [RFC4880], "Public-Key Packet Formats", to support ECDH and ECDSA.
```

**Comment by falko-strenzke** [comment]
Meeting 2023-06-05:
* AW has it still on his list, will make these cosmetic changes

**Comment by falko-strenzke** [comment]
@wussler @TJ-91 Can anyone say what is the status of this? I am not entirely certain anymore, what we had in mind here.

**Comment by wussler** [comment]
Still TODO
