### ISSUE TITLE
Should we point to https://datatracker.ietf.org/doc/draft-ounsworth-cfrg-kem-combiners/

### ISSUE THREAD

**Issue by fluppe2** [openpgp-pqc/draft-openpgp-pqc#17]
Such that our proposal for KEM combination automatically docks to the discussion of this draft?

**Comment by falko-strenzke** [comment]
Minutes Meeting 2023-01-19:

* Stavros: expect to be discussed in CFRG and our construction is an instance of this
* Aron: wait until CFRG has given a vote
* Andreas: what ounsworth needs is a dual-prf, but we use SHA3 which is thus a dual-prf
* Andreas: the simple way is to just concat everything into a KDF, but this is not addresing the attacks that were pointed out some time ago. 
* Stavros: we can decide whether to include reference
* Andreas, Stavros: when CFRG has voted, add statement to sec. considerations

**Comment by wussler** [comment]
Wait until https://github.com/EntrustCorporation/draft-ounsworth-cfrg-kem-combiners/pull/9 is merged

**Comment by falko-strenzke** [comment]
Meeting 2023-06-05:

  * AW: cannot point there currently as construction is still different
  *     Wait for my PR there to be merged then can point to it

**Comment by falko-strenzke** [comment]
@wussler What about the status of this? Can we / should we add the pointer here now? Or can we close this anyway?

**Comment by wussler** [comment]
Adoption call is ongoing right now, let's see what's the outcome next week

**Comment by wussler** [comment]
This was discussed at IETF 119 as well, for now we use the agreed constructions, with the idea that it might be provisional if CFRG produces an outcome

**Comment by wussler** [comment]
Merged into https://github.com/openpgp-pqc/draft-openpgp-pqc/issues/127
