### ISSUE TITLE
"Session Key" is unclear / inconsistent with Crypto Refresh

### ISSUE THREAD

**Issue by TJ-91** [openpgp-pqc/draft-openpgp-pqc#27]
The encryption/decryption of the session key is not sufficiently described and inconsistent with the Crypto Refresh.

In the Crypto Refresh for PKESKv5, we do not encrypt the session key itself, but the session key + 2 checksum bytes (for PKESK v3 also an algorithm identifier is included). The PQ/T algorithms should therefore encrypt the session key + checksum as well and it should be made explicit to the reader. I realize that the key wrap itself already has an integrity check but there is no harm in including the checksum bytes. Otherwise we explicitly have to deviate from the standard PKESK format which introduces an unnecessary special case.

Then, the additional problem of AES Key Wrap (RFC3394) only accepting data with length of multiples of 8 bytes arises: With the checksum, the key has improper length. The crypto refresh already uses pkcs5/pkcs7 padding for ECDH (Section 12.5).
We can do the same or use another method, e.g., there exists RFC5649 which extends the AES Key Wrap with padding.
Even if it is decided to only wrap the session key without a checksum, we should include some form of padding. This reduces the risk of future incompatibilities if (for whatever reasons) there are symmetric algorithms with key sizes that are not multiples of 64 bit.

Relevant lines in the Crypto Refresh for the ECDH encryption (Section 12.5):
```
m = symm_alg_ID || session key || checksum || pkcs5_padding;
```
```
Compute C = AESKeyWrap( Z, m ) as per [[RFC3394](https://www.rfc-editor.org/info/rfc3394)]
```

**Comment by falko-strenzke** [comment]
I don't think this is inconsistent with the crypto-refresh. The checksum is not part of the v5 PKESK specification, but only of the ECDH specification. And we are defining an alternate algorithm, so we are not at all bound to align it with the existing ECDH specification. I think this part is intentional. Otherwise, which part of the specification in our draft would you want to change and how?

Regarding the AES-Keywrap, without the checksum we wouldn't have that problem. But if I remember correctly, Aron intended to use the RFC 5649 key wrap that doesn't have this limitation. @wussler Is that correct?

**Comment by wussler** [comment]
I don't think we need the checksum bytes, they are already included in the AES wrapping.

I had also considered upgrading the wrapping, but it's useless: we don't need padding at all, unless we want to support ciphers with keys not multiple of 8 bytes.

Check out this 4880bis MR: https://gitlab.com/openpgp-wg/rfc4880bis/-/merge_requests/223/diffs

Also, from the minutes of the meeting:

> Remove checksum and padding for v5 PKESK? This reduces the bytes on the wire at no loss of functionality as there is already a checksum in the key wrapping algorithm.
MR that does this: !223
...
> dkg: poll: shall we simplify v6 ECDH PKESK keywrap input?
> dkg: 5 for, 0 against. Fewer people are actively engaging, but no one is objecting.
stephen: we're 90 minutes in, let's speed up
​

--
Aron Wussler
Sent with ProtonMail, OpenPGP key 0x7E6761563EFE3930

-------- Original Message --------

**Comment by falko-strenzke** [comment]
Here we don't have to consider ciphers as v5 PKESK session keys are only used in v2 SEIPD which  use the session key as input to the key derivation. Thus I wouldn't see a problem without the padding.

**Comment by wussler** [comment]
Very good point @falko-strenzke. I think this should be reflected on the rfc4880bis PR too, as this comment from dkg may be misleading, I got tricked by it too. The random material for key derivation could always be defined by rounding up to 8 bytes in future cipher constructions if needed.

In general I think this discussion is more relevant on the refresh if we decide to adopt this for v5 pkesk. Once we have a constraint there we gotta live with it.

--
Aron Wussler
Sent with ProtonMail, OpenPGP key 0x7E6761563EFE3930

-------- Original Message --------

**Comment by wussler** [comment]
This passed on the C-R, therefore seems clear here
