### ISSUE TITLE
Bump versions to v6

### ISSUE THREAD

**Issue by wussler** [openpgp-pqc/draft-openpgp-pqc#29]
Bump PKESK, Signature and Key version to v6 according to crypto-refresh

**Comment by fluppe2** [comment]
I would propose to bump the version once draft-08 of the crypto-refresh has been published (that incorporates [!231](https://gitlab.com/openpgp-wg/rfc4880bis/-/merge_requests/231). Right now the crypto-refresh it is still draft-07 and referring to v5 packets.
