### ISSUE TITLE
SHA-3 vs KMAC for KDF

### ISSUE THREAD

**Issue by teythoon** [openpgp-pqc/draft-openpgp-pqc#46]
Are there specific reasons for preferring KMAC over HKDF as key combiner?  Seeing that v6 OpenPGP now uses HKDF everywhere, it seems tempting to also use it as combiner to reduce the number of required algorithms, no?

**Comment by falko-strenzke** [comment]
The problem, as far as I understand it, is that HKDF is HMAC-based and HMAC does not qualify as a dual-PRF, which is what is needed when a secret shall be derived from two input keys: https://datatracker.ietf.org/meeting/113/materials/slides-113-cfrg-a-dual-prf-construction-00#page=8

**Comment by teythoon** [comment]
I don't understand.  The authors of the document are indeed using HMAC, albeit with an expansion step before, and they are doing HMAC twice, once with key 1 as key input and key 2 as data, the second time with the inputs swapped for symmetry, then xoring the HMAC outputs.

In contrast, this document simply does `KMAC(key1 || key2)`.  I don't understand why that should be a dual-PRF whereas `HKDF(key1 || key2)` should not be one.

Please unconfuse me.

The reason I'm bringing this up is that KMAC seems not to be widely available in cryptographic libraries.  A quick survey of the five cryptographic libraries that Sequoia can use paints a bleak picture:

- Nettle: not implemented
- OpenSSL: implemented in some versions, but not available in the bindings
- Botan: implementation in progress
- Rust: planned
- CNG: only in very new versions (starting with Windows 11 Preview Build 25324)

In contrast, HKDF (and HMAC) is available in all libraries in all versions we support.

**Comment by falko-strenzke** [comment]
I completely understand the problem regarding the implementation aspect. Regarding the theoretical questions, I cannot address them profundly. But yes, I would also assume that an HMAC-based and thus also HKDF-based construction should be possible. It might be far from optimal in terms of efficiency though. If that doesn't matter, we could try to figure out whether this is possible.

The reason why KMAC yields a dual-PRF simply with concatenation of the keys is apparently because it is based on SHA-3. When talking about HMAC above, I refer only (and also the authors of the slides, I assume) about HMAC using SHA-2.

**Comment by teythoon** [comment]
I see the statement "HMAC is generally not a dual-PRF." in the slides, but I don't see the assertion that KMAC should be one.

**Comment by falko-strenzke** [comment]
> I see the statement "HMAC is generally not a dual-PRF." in the slides, but I don't see the assertion that KMAC should be one.

Yes, sure. That work apparently does not deal with SHA-3 as dual-PRF at all. For these considerations you will have to look  into the security considerations of [draft-ounsworth-cfrg-kem-combiners](https://datatracker.ietf.org/doc/draft-ounsworth-cfrg-kem-combiners/) (which is work in progress, though, and might not be up to date). This was also discussed on the CFRG mailing list, see for instance [here](https://mailarchive.ietf.org/arch/msg/cfrg/LYkaqKMS2yIWqkHKASWbZ9aHhTY/)

**Comment by falko-strenzke** [comment]
By the way, this is the paper to the slides mentioned above: https://eprint.iacr.org/2022/065.pdf

**Comment by falko-strenzke** [comment]
Note that the [draft-ounsworth-cfrg-kem-combiners](https://github.com/EntrustCorporation/draft-ounsworth-cfrg-kem-combiners/blob/master/draft-ounsworth-cfrg-kem-combiners.txt) also allows for 

* KDF = SHA3-256 and
* KDF = SHA3-512

**Comment by teythoon** [comment]
Yeah, the SHA3-based combiners seem to be easier to implement on top of existing primitives.

**Comment by falko-strenzke** [comment]
I've made a corresponding PR: https://github.com/openpgp-pqc/draft-openpgp-pqc/pull/48

**Comment by wussler** [comment]
And as a small PS: since we're all gonna be at the summit, let's have a chat there about this :)

**Comment by teythoon** [comment]
> Finally Nettle offers [shake256 with context](https://docs.rs/nettle-sys/latest/nettle_sys/fn.nettle_sha3_256_shake.html), and rust offers [sha3::CShake256Core](https://docs.rs/sha3/latest/sha3/struct.CShake256Core.html) upon which KMAC can be built as [we did in golang](https://github.com/ProtonMail/go-crypto/blob/3d33cfd85858654533d5ab2728c4048dadccc87b/internal/kmac/kmac.go). OpenSSL seems indeed not to offer the bindings, and I hope to be wrong, but seems like CNG [does not even offer SHA3](https://learn.microsoft.com/en-us/windows/win32/seccng/cng-algorithm-identifiers).

That is good to hear, I didn't realize that, and indeed that seems like something we could steal^Wadapt.  I'm sure the OpenSSL bindings can be easily extended.  CNG gets Keccak-based constructions "soon", but it will be quite some time until people can rely on that being available.  But in the mean time, we will augment CNG with algorithms from RustCrypto, as we do for other algorithms (notably, Ed25519... wtf CNG...)

https://blogs.windows.com/windows-insider/2023/03/23/announcing-windows-11-insider-preview-build-25324/

I guess that addresses my concern.

**Comment by wussler** [comment]
Hi, as said on the PR #48, I would keep this issue open in order to see if the implementation turns out to be too complex here for other parties too, or if there is any slightly more complex SHA-3 construction that could give us the same properties (for our limited use scenario) for a lower implementation cost.

Thanks for looking into this @teythoon!

**Comment by ounsworth** [comment]
Hey @teythoon and @falko-strenzke, @wussler, sorry for being _very_ late at the party.

I am not going to wade into the theoreticals -- that's what Falko, Aron, and Stavros are for ;) -- but we already faced criticism that 

```
KDF(counter || k_1 || ... || k_n || fixedInfo, outputBits)
where
k_i = H(ss_i || ct_i)
```
is too many invocations of `H`, and thus as a consolation to performance, we also offer
```
k_i = ss_i || ct_i
```
when safe.

Given this, I cannot imagine that the construction from [2022/065] will be well received given that involves the expander

```
F(k) = H(0||k1)||H(1||k1)||...||H(j||k1)||H(0||k2)||H(1||k2)||...||H(j||k2)||H(0||Kn)||H(1||Kn)||...||H(j||kn)
```
which I believe calls `H()` 3x for each block of input.

So I think the debate comes down to how much the dual-PRF property matters in practice. 

@wussler would there be any harm in adding the [2022-065] combiner to draft-ounsworth-cfrg-kem-combiners as a "paranoid level" option?

**Comment by teythoon** [comment]
> Finally Nettle offers [shake256 with context](https://docs.rs/nettle-sys/latest/nettle_sys/fn.nettle_sha3_256_shake.html)

FTR, that is a misunderstanding.  The context in the function signature is the context object for the Shake operation, not the context in the cryptographic context sense.

Nevertheless, I am convinced that KMAC will be the least of our problems algorithm-wise, and we'll depend on Botan which has KMAC for the PQ algorithms in the short-term anyway.  So yeah, my concern is sufficiently addressed, thanks for bearing with me.
