### ISSUE TITLE
Hash binding too restrictive?

### ISSUE THREAD

**Issue by falko-strenzke** [openpgp-pqc/draft-openpgp-pqc#57]
The specification of the hash binding currently doesn't allow the stronger hash functions (SHA512 vs. SHA256 and SHA3-512 vs. SHA3-256) for the smaller PQC signature parameter sets. But I think this restriction doesn't make sense. We should better both hash algorithms of the respective family for the smaller parameter set.

**Comment by fluppe2** [comment]
Why should one go with SHA512 or SHA3-512 when using the Category 3 parameter sets? It shoudl be rather SHA384 or SHA3-384 for Cat. 3. But this is somehow not present in OpenPGP, is it?

However, let's discuss it.

**Comment by wussler** [comment]
I think #60 addresses this well

**Comment by fluppe2** [comment]
We should discuss that interactively during a meeting. I have no objections allowing more signature data digest algorithms, but I don't know if that is what is wanted in terms of simplicity.


BTW: SHA3-256 seems to be an odd choice when you aim for NIST security level 3 Dilithium, as SHA3-256 is level 2. I understand that we chose this due to lacking support for SHA3-384 in the crypto-refresh, but do we really want to go with this or ask for the inclusion if SHA3-384?

**Comment by wussler** [comment]
Isn't SHA2-256 level 2? Or also SHA3?

**Comment by fluppe2** [comment]
See https://csrc.nist.gov/projects/post-quantum-cryptography/post-quantum-cryptography-standardization/evaluation-criteria/security-(evaluation-criteria)

1. Any attack that breaks the relevant security definition must require computational resources comparable to or greater than those required for key search on a block cipher with a 128-bit key (e.g. AES128)

2. Any attack that breaks the relevant security definition must require computational resources comparable to or greater than those required for collision search on a 256-bit hash function (e.g. SHA256/ SHA3-256)

3. Any attack that breaks the relevant security definition must require computational resources comparable to or greater than those required for key search on a block cipher with a 192-bit key (e.g. AES192)

4. Any attack that breaks the relevant security definition must require computational resources comparable to or greater than those required for collision search on a 384-bit hash function (e.g. SHA384/ SHA3-384)

5. Any attack that breaks the relevant security definition must require computational resources comparable to or greater than those required for key search on a block cipher with a 256-bit key (e.g. AES 256)

**Comment by fluppe2** [comment]
With a randomized digest you do not rely on collision resistance. But do people understand this? I guess a straight-forward combination is SHA(3)-384 with Dilithium Level 3. My concern is only that other working groups might look what "they" did in OpenPGP and simply copy the combinations without having the expertise to judge if the combination is fine. However, maybe SHA3-256 is fine if you argue that the randomization ensures that an attacker has to find a preimage and that cost is higher than finding a collision.

**Comment by falko-strenzke** [comment]
Draft team meeting 2023-09-11: Agrees to leave hash-bindings as specified currently.
