### ISSUE TITLE
Consistency in the KEM descriptions

### ISSUE THREAD

**Issue by teythoon** [openpgp-pqc/draft-openpgp-pqc#68]
Section 5.1.2 about ML-KEM starts with

> 1. Extract the encapsulation key mlkemPublicKey that is part of the recipient's composite public key

but in the description of X*-KEM and ECDH-KEM, the recipients pubic key appears out of nowhere.  I think this should be made consistent, one way or the other.

**Comment by falko-strenzke** [comment]
Now addressed in https://github.com/openpgp-pqc/draft-openpgp-pqc/pull/80

**Comment by falko-strenzke** [comment]
Closing as fixed in #80
