### ISSUE TITLE
Mandatory AES for v3 PKESK: AES is not a MUST in RFC4880

### ISSUE THREAD

**Issue by falko-strenzke** [openpgp-pqc/draft-openpgp-pqc#74]
Currently our draft states (slightly revised text in my working branch) for ML-KEM cmposite encryption:

> Note that unlike most public-key algorithms, in the case of a v3 PKESK packet, the symmetric algorithm identifier is not encrypted. Instead, it is prepended to the encrypted session key in plaintext. In this case, the symmetric algorithm used MUST be AES-128, AES-192 or AES-256 (algorithm ID 7, 8 or 9).

But this isn't possible with RFC 4880 to which we aim to be compatible here, as there AES-128 is only a SHOULD. The only MUST symmetric algorithm there is TripleDES. So either we require at the same time with introducing PQC that AES-128 becomes a MUST, which seems a bit strange to me, or we have to keep the symmetric algorithm flexible, which would make the most sense in my opinion.

From a practical perspective requiring AES-128 as MUST is most likely realistic. But from a formal perspective it means that a sending client conforming to RFC 4880 and sending an encrypted mail to multiple recipients, some supporting ML-KEM, some not, could come into the conflict of having to use AES-128 for the PQC supporting recipients and TripleDES for the legacy clients. Actually the similar but even bigger problem can happen to a client supporting the crypto-refresh and sending to mutiple clients, since the crypto-refresh even completely forbids TripleDES.

So should we simply assume that clients today all support AES-128?

@TJ-91 @wussler @fluppe2

**Comment by wussler** [comment]
> Stay consistent with the Crypto Refresh and assume AES is always supported and add some text to address this issue.

This is my preferred approach. We use AES Key Wrap, and makes no sense to extend the attack surface by adding TripleDES support (or any other algorithm).

Note that we can just make AES mandatory in this draft, and I would have no issue doing so. Implementing the latest PQC algos to then use CAST5 feels very silly.

**Comment by dkg** [comment]
I agree with @wussler that just mandaing AES here is the only thing that makes sense.  This is a weird backward-compatible thing, even bothering with the deprecated PKESKv3/SEIPDv1 approach; it doesn't need to be backward-compatible with every possible historical wart of OpenPGP.

If anyone is aware of an OpenPGP implementation that has any sort of vaguely active maintenance but cannot do AES, please point to it.

**Comment by falko-strenzke** [comment]
OK, so what remains is to decide whether we add an explicit note somewhere in the draft that with the introduction of PQC, AES-128 is considered to be mandatory to implement. A reference to the crypto-refresh would also make sense here.

**Comment by wussler** [comment]
Note that we use AES-KW in the algorithm itself, I can't imagine an implementation supporting AES-KW and not AES-128 as a symmetric algo. I am in favor of making AES-128 mandatory to implement.

**Comment by fluppe2** [comment]
I would rather specify AES-256 as MUST. Keep in mind that
- the security niveau of AES-128 doesn't match the one for pqc level 3 and 5 parameter sets, AES-128 is NIST level 1
- AES-192 (as a match for the entry level pqc security niveau, i.e. NIST level 3) feels like a peculiar choice, who is using that?
- we use AES-256 for the key wrap anyway.

AES-256 (instead of AES-128) as MUST in the pqc draft feels like the more correct choice to me

**Comment by wussler** [comment]
Agreed with @fluppe2 I think this is a very coherent choice

**Comment by fluppe2** [comment]
Yes, I guess "coherent" is the right word here. When it comes to quantum-safety the international recommendation (e.g. CNSA 2.0, ANSSI, BSI) is to use AES-256. So why not just pin AES-256 to the wall.

**Comment by falko-strenzke** [comment]
Thanks for the clarification Johannes. I think from this it is clear that we must be careful not to introduce any interoperability issues. Moving to AES-128 as mandatory is in line with the crypto-refresh and thus reasonable, but moving beyond that (i.e., to AES-256) would create interoperability issues.

**Comment by wussler** [comment]
@TJ-91 
> First, Stavros and Aron, you seem to be mixing "per-recipient stuff" and "per-message stuff" up. We do use AES Key Wrap as part of the PKESK packets (for X2559/X448/PQC keys), which are per-recipient.

True, indeed here we might be mixing PQ and traditional recipients. This would have definitely been simpler by limiting encryption to v6, but I still see the advantage of having v4 PQC.

> Even requiring AES-128/192/256 for the PKESKv3 case as we (and the Crypto Refresh) currently do is not really "natural" for the protocol. Or am I severely misunderstanding something?

Here, I think it's okay. Implementations go forward, and if you are that outdated that you don't support AES, I would blame the person still relying on 3des in 2024.

As @dkg  pointed out
> If anyone is aware of an OpenPGP implementation that has any sort of vaguely active maintenance but cannot do AES, please point to it.

That I know of, there is no implementation not supporting all flavors of AES.

Re @falko-strenzke 
> Moving to AES-128 as mandatory is in line with the crypto-refresh and thus reasonable, but moving beyond that (i.e., to AES-256) would create interoperability issues.

I would still be in favor of mandating support of AES-256, and in the long run, when sending PQ-only messages we might be able to enforce it. We'd still allow AES-128 for v3 PKESK, and make mandatory AES-256 support (coherently with PQ requirements and the KW).

**Comment by falko-strenzke** [comment]
> That I know of, there is no implementation not supporting all flavors of AES.

Yet still, the crypto-refresh did not make AES-256 MUST for some reason, but only SHOULD. Before going one step furhter than the c-r, I would ask the WG about this. 

As I understand, we agree that use of AES-256 as the symmetric algorithm can only happen if all recipients are found to support it. If we make AES-256 a MUST for PQC, then, if a recipient has at least one PQC key, this could be used to assert that they support AES-256. Possibly we would want to bind it only to the existence of PQC encryption key.

**Comment by falko-strenzke** [comment]
> As an alternative to @falko-strenzke's proposal we can simply mandate that AES-256 **MUST** be part of the preferred SEIPDv1 / AEAD subpackets if the certificate has a PQ(/T) encryption key. I think that is uncontroversial and it wouldn't make sense to leave it out. We can further mandate that when encrypting to multiple recipients, and all recipients support AES-256, and at least one PKESK uses a PQ(/T) key, then AES-256 has to be chosen for the symmetric encryption.

👍
> 
> Perhaps it could be loosened to the requirement that "Level 3" keys only require AES-192 to be supported, but that's not an important decision for now.

I would leave out AES-192, from what I understood it is generally considered to be not so well supported.

**Comment by dkg** [comment]
@TJ-91 wrote:
> What I meant is that mandating a specific symmetric algorithm that has to be used in combination with a specific public-key encryption algorithm violates the separation that OpenPGP used to have between the two kinds of encryption.

I agree with Johannes here that this "violates the separation that OpenPGP used to have", but i'm also not convinced that the separation is entirely healthy.  I'll note that another aspect of this draft also "violates" a traditional OpenPGP separation: the `SLH-DSA` signatures are obliged to use specific choices of digest algorithm for the message. Traditionally, OpenPGP messages could select any digest algorithm with any asymmetric signature primitive.  This isn't exactly the same thing as binding the symmetric cipher to the PKESK choice, of course (for one thing, if you can't read signature A you might still be able to read signature B), but "violating a traditional separation" as a general practice isn't necessarily a bad thing.

Anyway, i don't see why it would be an objection here, especially given that everyone, everywhere, that has any chance of reading a recent encrypted message appears to support both AES-128 and AES-256.

**Comment by dkg** [comment]
@TJ-91 wrote:
> we can simply mandate that AES-256 **MUST** be part of the preferred SEIPDv1 / AEAD subpackets if the certificate has a PQ(/T) encryption key.

I like this idea, but a couple notes of caution:

- remember that the `AEAD ciphersuite preferences` packet has an implicit `AES-128,OCB` tacked on at the end if it doesn't explicitly contain it, due to the MTI algorithms in the crypto-refresh.
- saying "`MUST` be part of" implies that an OpenPGP certificate without it is inherently a malformed protocol data unit; what should a receiving OpenPGP implementation do with such an object?  reject it?  report it? refuse to use it?

Rather than introducing new failure mode, wouldn't it be more straightforward to say that there is an implicit `AES-256,OCB` in the `AEAD Ciphersuite Preferences` for any such public key, aligned with the implicit `AES-128,OCB` entry?

**Comment by dkg** [comment]
I think it might be simplest to say that, for keys like this:

- the implicit list at the end of SEIPDv1 preferences is `AES-256`, `AES-128`.

- the implicit list at the end of SEIPDv2 preferences is `AES-256+OCB`, `AES-128+OCB`.

**Comment by wussler** [comment]
I agree this to be a good solution, and our first chance of reporting a substantiating change to the list

**Comment by dkg** [comment]
On Wed 2024-02-07 09:00:01 -0800, dkg wrote:
> - the implicit list at the end of SEIPDv1 preferences is `AES-256`, `AES-128`.

After sleeping on it, i think the above change might be the only thing
needed, since it relates to the PKESKv3 silliness.

> - the implicit list at the end of SEIPDv2 preferences is `AES-256+OCB`, `AES-128+OCB`.

This one doesn't seem strictly necessary (PKESKv6's KDF folds in the
algorithm ID, so there's no risk of cross-algorithm key mis/re-use).

If we want to include it, we should include it by making an explicit
"needed for post-quantum" argument.

**Comment by dkg** [comment]
@TJ-91 thanks for the clarification, i think you're right that i got a bit confused by the overlapping topics.

And whether it's "needed" or not, it does make sense that if the asymmetric operation embeds the use of AES256 keywrap, it ought to have implied support for AES256 as a symmetric cipher.
