### ISSUE TITLE
clarify x25519 wire format

### ISSUE THREAD

**Issue by dkg** [openpgp-pqc/draft-openpgp-pqc#77]
draft-ietf-openpgp-pqc-00 currently says:

> For Curve25519 this specification adapts the encoding of objects as defined in [[RFC7748](https://www.ietf.org/archive/id/draft-ietf-openpgp-pqc-00.html#RFC7748)] in contrast to [[I-D.ietf-openpgp-crypto-refresh](https://www.ietf.org/archive/id/draft-ietf-openpgp-pqc-00.html#I-D.ietf-openpgp-crypto-refresh)].

What does this sentence mean?  is "adapt" supposed to mean "adopt"?  In this context, adapt typically means "modifies to fit", while "adopt" typically means "embraces as specified".  the crypto-refresh draft itself uses RFC 7748 for X25519: https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-13.html#section-5.1.6  There is of course Curve25519Legacy (https://www.ietf.org/archive/id/draft-ietf-openpgp-crypto-refresh-13.html#section-5.5.5.6.1.1) but that is deprecated and not the recommended approach.

**Comment by falko-strenzke** [comment]
I think you are entirely right. I am quite sure the text you are referring to was written before the crypto-refresh received the new X25519. I integrated my proposed fix in my recent PR https://github.com/openpgp-pqc/draft-openpgp-pqc/pull/80. Please check if that fixes the issue.

**Comment by falko-strenzke** [comment]
Closing it as fixed in #80
