### ISSUE TITLE
IANA protocol tables references need updating

### ISSUE THREAD

**Issue by dkg** [openpgp-pqc/draft-openpgp-pqc#82]
draft-ietf-openpgp-crypto-refresh provided a significant update to the IANA registries relevant to OpenPGP.

Please go through the draft and ensure that any IANA requests are aligned with the tables [as currently described](https://www.iana.org/assignments/openpgp/openpgp.xhtml).

**Comment by falko-strenzke** [comment]
addressed in https://github.com/openpgp-pqc/draft-openpgp-pqc/pull/85
