### ISSUE TITLE
mail weekly github summary to mailing list

### ISSUE THREAD

**Issue by dkg** [openpgp-pqc/draft-openpgp-pqc#84]
We want a weekly summary of github activity to go to the [openpgp@ietf.org mailing list](https://www.ietf.org/mailman/listinfo/openpgp).  I'll work on setting this up.

**Comment by dkg** [comment]
This is now done.  First message went out yesterday: https://mailarchive.ietf.org/arch/msg/openpgp/ahQNeRkwEPqpgANokKX8Jh8F4x0

**Comment by falko-strenzke** [comment]
Great, thank you!
